services:
  app:
    build: .
    image: huohen92/qqmusic-monitor:v0.9.3
    container_name: QQMusic-monitor
    ports:
      - "6696:6696"
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    restart: always
